# Generated by Django 4.2.3 on 2023-07-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_produto', models.PositiveBigIntegerField()),
                ('nome_produto', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('quantidade', models.PositiveIntegerField()),
            ],
        ),
    ]
